/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cards/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Url */
        post: operations["create_upload_url_cards_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_cards_get"];
        put?: never;
        /** Add Card */
        post: operations["add_card_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_cards__card_id__get"];
        put?: never;
        post?: never;
        /** Delete Card */
        delete: operations["delete_card_cards__card_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/webhooks/card-created": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle Card Created */
        post: operations["handle_card_created_cards_webhooks_card_created_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Card */
        Card: {
            /** Ref Card Id */
            ref_card_id?: string | null;
            /** User Id */
            user_id: string;
            /** Image Path */
            image_path: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** @default pending */
            matching_status: components["schemas"]["MatchingStatus"];
        };
        /** CardRead */
        CardRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref Card Id */
            ref_card_id: string | null;
            /** User Id */
            user_id: string;
            /** Image Path */
            image_path: string;
            matching_status: components["schemas"]["MatchingStatus"];
        };
        /** CreateCardPayload */
        CreateCardPayload: {
            /** Image Path */
            image_path: string;
        };
        /** CreateCardSignedUploadUrl */
        CreateCardSignedUploadUrl: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MatchingStatus
         * @enum {string}
         */
        MatchingStatus: "pending" | "matched" | "failed";
        /**
         * PubSubEnvelope
         * @description Pub/Sub push subscription envelope.
         */
        PubSubEnvelope: {
            message: components["schemas"]["PubSubMessage"];
            /** Subscription */
            subscription: string;
        };
        /**
         * PubSubMessage
         * @description Pub/Sub message structure.
         */
        PubSubMessage: {
            /** Data */
            data: string;
            /** Messageid */
            messageId: string;
            /** Publishtime */
            publishTime: string;
        };
        /** UploadUrlResponse */
        UploadUrlResponse: {
            /** Upload Url */
            upload_url: string;
            /** Image Path */
            image_path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** RefCardRead */
        RefCardRead: {
            /** Tcg Id */
            tcg_id: string;
            /** Tcg Local Id */
            tcg_local_id: string;
            /** Name */
            name: string;
            /**
             * Image Url
             * @default null
             */
            image_url: string | null;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** TcgSetRead */
        TcgSetRead: {
            /** Tcg Id */
            tcg_id: string;
            /** Name */
            name: string;
            /**
             * Year
             * @default null
             */
            year: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_upload_url_cards_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardSignedUploadUrl"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"][];
                };
            };
        };
    };
    add_card_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    handle_card_created_cards_webhooks_card_created_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PubSubEnvelope"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
